kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes: # we are requiring one control-plane and 3 worker nodes
  - role: control-plane
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2  
    extraPortMappings: # expose ports 80 and 443
      - containerPort: 80 # http port
        hostPort: 80
        protocol: TCP
      - containerPort: 443 # https port
        hostPort: 443
        protocol: TCP