kind: Deployment
apiVersion: apps/v1

metadata:
  name: nginx-deployment
  namespace: example-ingress-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
