kind: Service
apiVersion: v1

metadata:
  name: mysql-service
  namespace: mysql-ns

spec:
  clusterIP: None # Only accessible inside the cluster, no external access 
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
